### ISSUE TITLE
Add documentation and blog post about font installs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#388]
Fontist and font installs, how to use the latest Metanorma CLI.

**Comment by ronaldtse** [comment]
Should cover text from:
* https://github.com/metanorma/metanorma-docker/issues/99
* https://github.com/metanorma/metanorma/issues/184

**Comment by CAMOBAP** [comment]
@ronaldtse we already have https://www.metanorma.org/blog/2021-01-24/fonts-related-options-metanorma-cli/

But I agree, it looks like fonts-related options really block/confuse our users.
We should attract more attention of our users to this topic (on metanorma.com)

Here is my proposal:
 - Maybe we should 'move' it to https://www.metanorma.org/author/ section to make it easy to find
 - It's impossible to find any post/doc by search 'font' word (screenshot attached). I didn't found any tags, topics that allow making posts 'visible' for search.
 - Add information about how 'cache' fonts with docker based on feedback in metanorma/metanorma-docker#99 and metanorma/metanorma-docker#99

<img width="791" alt="Screen Shot 2021-05-01 at 9 56 36 AM" src="https://user-images.githubusercontent.com/2169738/116774475-7ec21700-aa65-11eb-81ff-a8f53041d29e.png">


@ronaldtse let me know how do you think?

**Comment by CAMOBAP** [comment]
@ronaldtse to be on the same page, do you agree with my proposals in the comment above?

**Comment by ronaldtse** [comment]
@CAMOBAP fully agree. Please proceed, thanks!

**Comment by CAMOBAP** [comment]
- [x] 'move' a fond related article to https://www.metanorma.org/author/ section to make it easy to find
It's impossible to find any post/doc by search 'font' word (screenshot attached). I didn't found any tags, topics that allow making posts 'visible' for search.
- [x] Add information about how 'cache' fonts with docker based on feedback in metanorma/metanorma-docker#99 and metanorma/metanorma-docker#99
- [ ] It's impossible to find any post/doc by search 'font' word (screenshot attached). I didn't found any tags, topics that allow making posts 'visible' for search.
- [ ] Fix white font color in search input

**Comment by ronaldtse** [comment]
FYI @metanorma/editors another FAQ kind of content we need to consider.

**Comment by CAMOBAP** [comment]
PR https://github.com/metanorma/metanorma.org/pull/436 which fix two issues from https://github.com/metanorma/metanorma.org/issues/388#issuecomment-855436056 

I didn't manage to fix:
 - white font color for search text field
 - it doesn't clear how search works at all if we don't have `algolia` gem dependency (maybe it comes implicitly)

**Comment by CAMOBAP** [comment]
@strogonoff maybe you can help  with those two last items in https://github.com/metanorma/metanorma.org/issues/388#issuecomment-855436056 or clarify  https://github.com/metanorma/metanorma.org/issues/388#issuecomment-856678509 about algolia?

**Comment by CAMOBAP** [comment]
@ronaldtse @strogonoff could you please review https://github.com/metanorma/metanorma.org/pull/436 and https://github.com/metanorma/metanorma.org/issues/388#issuecomment-856678509 comment

**Comment by ronaldtse** [comment]
Yup will do today. Sorry for delay…

**Comment by ronaldtse** [comment]
This is finally done. Thanks @CAMOBAP !
