### ISSUE TITLE
Build failure in site due to jekyll-theme-open-project

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#431]
https://github.com/metanorma/metanorma.org/runs/2703600508?check_suite_focus=true

Issue:
https://github.com/riboseinc/jekyll-theme-open-project/issues/77

**Comment by ronaldtse** [comment]
This is blocking #429

**Comment by ronaldtse** [comment]
@strogonoff this default to "master" is blocking deployment of all open projects.

**Comment by strogonoff** [comment]
> @strogonoff this default to "master" is blocking deployment of all open projects.

@ronaldtse  Are all projects using “main” now? Which is more common, `main` or `master`? To know what should be the default option.

**Comment by strogonoff** [comment]
Fixed upstream issues: https://github.com/riboseinc/jekyll-theme-open-project-helpers/issues/20 and https://github.com/riboseinc/jekyll-theme-open-project/issues/77.

* Open project framework now uses “main” as default. 
* Custom branch can be specified for most (all?) repos.
* A number of repos are still using “master”. As we migrate those repos to “main”, please make sure to update corresponding YAML structures (see changes in 12fad0bce527ab9476f53c77c3942bd721ab4a01, 13a1db4aa8d0c2d01ca852db1f4efba881fcf9ad, 0dae40f7f483afb862658eaa7162a61ae8fd5c1e for non-standard references).

cc @ronaldtse

**Comment by ronaldtse** [comment]
Thank you @strogonoff ! Confirm that it works great.
