### ISSUE TITLE
"Suggest edits to the page" Links are outdated

### ISSUE THREAD

**Issue by kickoke** [metanorma/metanorma.org#440]
Hello folks, 
I've noticed my beloved functionality to access the corresponding file in the repository (Suggest edits to the page button) doesn't work anymore, due to changes in the URL.

Example: 
[Document Attributes](https://www.metanorma.org/author/ref/document-attributes/) links to 
https://github.com/metanorma/metanorma.org/edit/main/author/ref/document-attributes.adoc --> 404
The actual URL for this is:
https://github.com/metanorma/metanorma.org/blob/master/author/ref/document-attributes.adoc

The same error occurs for all other sites as well.
Is there an easy way to fix this?

**Comment by ronaldtse** [comment]
Thanks for discovering this issue @kickoke !

This issue stems from the latest branch name change from "master" to "main" for inclusiveness in the open-project code. I have just changed the branch of this repo to use "main" now, so it should work.

**Comment by ronaldtse** [comment]
Confirmed this is fixed.
