### ISSUE TITLE
Document possible locality options (`clause=`, `table=`, `figure=`, etc)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#482]
Right now the possible options are shown in examples but not explicitly listed. It also creates confusion whether something like `figure` is supported.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/11865/132271291-b59fac43-7b18-4ecc-af2d-b3afffc32ef0.png">

**Comment by opoudjis** [comment]
Already done:

https://www.metanorma.org/author/topics/document-format/bibliography/#localities
