### ISSUE TITLE
Document how to use `.mml` files from PDF accessibility for MathML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#484]
BIPM PDF contains attached files with .mml extension. Windows OS doesn't have the file association (by default) for .mml file extension. You need to set default application (Notepad for example) to open files with .mml extension:
- open the specified folder (`C:\....\Local\Temp\A9.tmp\`) in the Explorer, 
or 
- find any another .mml file, or create an empty file by the command `notepad sample.mml`
then
- right-click on .mml file and choose the default program to open .mml file (see how to: https://www.online-tech-tips.com/windows-10/how-to-change-file-associations-in-windows-10/)
- may be you need to re-run Acrobat (actually don't need to system reboot)

_Originally posted by @Intelligent2013 in https://github.com/metanorma/bipm-si-brochure/issues/152#issuecomment-914165009_

**Comment by ronaldtse** [comment]
We need a page on PDF accessibility.

**Comment by ronaldtse** [comment]
@Intelligent2013 indeed, we just need to copy/paste this information to a separate page about PDF accessibility.

**Comment by Intelligent2013** [comment]
> 
> 
> @Intelligent2013 indeed, we just need to copy/paste this information to a separate page about PDF accessibility.

@ronaldtse done.
