### ISSUE TITLE
Document how to setup macOS (and other platforms) for Metanorma development

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#496]
We used to recommend https://github.com/metanorma/metanorma-macos-setup/ but it is now archived/obsolete due to other user setup options.

However, we are now missing appropriate documentation for developers who wish to develop with Metanorma and/or use other Ruby tools (e.g. `stepmod-utils`) with Metanorma.

This task is to provide such documentation.

**Comment by ronaldtse** [comment]
So far I've been using something like this:

```sh
# Install Xcode and associated development tools
xcode-select —install

# Install GCC and development tools
brew install autoconf gcc make

# Install rbenv (the default macOS Ruby is used by system and can be tricky with installs/uninstalls)
brew install rbenv

# Install Ruby 2.7.4
rbenv install 2.7.4

# Install stepmod-utils
gem install stepmod-utils
```

However this set of commands may look different for M1:
https://github.com/rbenv/ruby-build/issues/1691

**Comment by CAMOBAP** [comment]
Done
