### ISSUE TITLE
Better document usage of `actions-mn/*`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#507]
Right now they are not well documented in `actions-mn`.

We have two actions:
* actions-mn/setup@v2
* actions-mn/cli/site-gen@main

We need better documentation:
* need explanation if there are any options (e.g. `with:`)
* how to set path of metanorma.yml for site generation (`actions-mn/cli/site-gen@main`)
* where is the site generated, there must be some options for site-get

This originates from #494 and #505

**Comment by CAMOBAP** [comment]
@ronaldtse I have added page https://www.metanorma.org/install/cicd/

But I don't think it makes sense to duplicate inputs documentation because all descriptions already available in action description

Let me know if anything else should be added
