### ISSUE TITLE
OGC guide: does highlighted text work in PDF?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#548]
Question for @Intelligent2013

**Comment by Intelligent2013** [comment]
@ronaldtse yes, `hi` tag processing added in https://github.com/metanorma/metanorma-ogc/issues/229.

Example:
adoc
```adoc
The CityGML Conceptual Model Standard defines a #common semantic information# model for the representation ...
```

mn xml:
```xml
<p id="_">The CityGML Conceptual Model Standard defines a <hi>common semantic information</hi> model for the representation ...
```
PDF:
![image](https://user-images.githubusercontent.com/5559926/147916352-a1702953-63ca-41ba-bd40-ddee28a6a1a5.png)
