### ISSUE TITLE
OGC guide: Add guidance on inserting a "literal" block / ASCII-art when doing a block indent

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#549]
Is it same as `[quote]` or `[source]`?

**Comment by opoudjis** [comment]
An Asciidoctor block indent, as in:

````
  Hello
````

is parsed as neither! It's parsed as a literal (ascii-art), which ends up in Metanorma XML as a figure: `<figure><pre>...</pre></figure>`.

The equivalence of block indent and explicit literal markup (`...`) is done by Asciidoctor itself, I cannot work around it.

If you want quote or source, you will have to mark them up as such explicitly.

**Comment by ronaldtse** [comment]
Thanks, we need to put this on the website because it is something OGC authors wish to know.
