### ISSUE TITLE
Windows install page does not tell user how to use it

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#569]
https://www.metanorma.org/install/windows
<img width="837" alt="Screenshot 2022-02-10 at 6 22 57 PM" src="https://user-images.githubusercontent.com/11865/153387344-2f51a139-22de-4834-9375-08a0275fc420.png">

It's called "Running Metanorma on Windows" so we ought to provide some instructions on how to run the installed package.

**Comment by CAMOBAP** [comment]
Other pages organized in a such way, there is no examples:
 - https://www.metanorma.org/install/linux/
 - https://www.metanorma.org/install/macos/
 - https://www.metanorma.org/install/windows/

I propose to:
 - [ ] Rename `Running Metanorma on $PLATFORM` to `Getting started with Metanorma on $PLATFORM`
 - [ ] Add link to Get started guide https://www.metanorma.org/author/getting-started/ in the end each install page

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP agree with the suggestion. Can you help make a PR for that?

**Comment by CAMOBAP** [comment]
> #569 add reference to metanorma-cli usage page #580

Sure, already done https://github.com/metanorma/metanorma.org/pull/580
