### ISSUE TITLE
Provide example of numeric references in documentation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#583]
This example is from ISO 10303-55 from @opoudjis.

These references have been marked up as:

`* [[[iso10303-49, (1)ISO 10303-49]]], _Industrial automation systems and integration — Product data representation and exchange — Part 49: Integrated generic resource: Process structure and properties._`

The `(1)ISO 10303-49` is requesting Metanorma to replace the identifier "ISO 10303-49" with a numeric identifier, and SUPPRESS the "ISO 10303-49" display. In the case of Bibliographies under ISO, this markup is unnecessary: the reference tag `ISO 10303-49` will give the correct output of a numbered bibliography entry, and will not suppress the SDO identifier.

(In fact, the HTML is rendering them correctly regardless.)

````
* [[[iso10303-49, ISO 10303-49]]], _Industrial automation systems and integration — Product data representation and exchange — Part 49: Integrated generic resource: Process structure and properties._

* [[[iso10303-21, ISO 10303-21]]], _Industrial automation systems and integration — Product data representation and exchange — Part 21: Implementation methods: Clear text encoding of the exchange structure._

* [[[iso10303-109, ISO 10303-109]]], _Industrial automation systems and integration — Product data representation and exchange — Part 109: Integrated application resource: Kinematic and geometric constraints for assembly models._

* [[[iso10303-203, ISO 10303-203]]], _Industrial automation systems and integration — Product data representation and exchange — Part 203: Application protocol: Configuration controlled design._

* [[[iso13584-20, ISO 13584-20]]], _Industrial automation systems and integration — Parts library — Part 20: Logical resource: Logical model of expressions._

* [[[hoffmann,6]]], HOFFMANN, C.M., _Geometric and Solid Modeling,_ San Mateo, CA: Morgan Kaufmann, 1989.

* [[[hoschek,7]]], HOSCHEK, J.; DANKWORT, W. (editors). _Parametric and Variational Design,_ Stuttgart: Teubner- Verlag, 1994.

* [[[rappaport,8]]], RAPPAPORT, A. _Breps as Displayable-Selectable Models in Interactive Design of Families of Geometric Objects_, in _Geometric Modeling: Theory and Practice_ (edited by W. Strasser, R. Klein and R. Rau); Berlin: Springer-Verlag, 1997.

* [[[shah,9]]], SHAH, J. J.; MÄNTYLÄ, M. _Parametric and Feature-based CAD/CAM,_ New York: Wiley, 1995.
````

<img width="916" alt="Στιγμιότυπο 2022-04-14, 00 32 25" src="https://user-images.githubusercontent.com/1911039/163204203-d5b59316-c2ed-475a-9758-aea581cce98d.png">

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-iso/issues/612#issuecomment-1098126874_

**Comment by manuel489** [comment]
Content provided. Closing.
