### ISSUE TITLE
Old documentation in the metanorma-* gems should all be removed and consolidated in this site

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#589]
e.g. metanorma-cc, metanorma-iso contain some documentation that are deprecated and misleading now. We need to remove all of them and move them into this site.

**Comment by opoudjis** [comment]
In the process, I am replacing links to /software/metanorma-cli in metanorma.org (which are loaded from the repo) with links to /install/man and /install/usage, drawn respectively from metanorma-cli/docs/usage and metanorma-cli/README

**Comment by opoudjis** [comment]
Done, but the newly added pages /install/man, /install/manual-installation, and /install/usage are indenting incorrectly, and I have no idea how to address that. @strogonoff ?

**Comment by strogonoff** [comment]
I can’t understand what “indenting” means…

**Comment by ronaldtse** [comment]
I think he means the hierarchical level in navigation.

**Comment by opoudjis** [comment]
If I open any of those pages, they are shifted left so that part of their text is off screen.

**Comment by strogonoff** [comment]
Which are the pages in question? https://www.metanorma.org/install/man/ doesn’t exist, is it in a branch?

**Comment by strogonoff** [comment]
This can be addressed by following frontmatter convention of sibling pages (specifying same layout and class).
