### ISSUE TITLE
Link broken in "Metanorma OGC sample" page

### ISSUE THREAD

**Issue by letmaik** [metanorma/metanorma.org#603]
https://www.metanorma.org/author/ogc/sample/

The link to "Metanorma for OGC" is broken.

**Comment by ronaldtse** [comment]
Thanks @letmaik !

@strogonoff do you have time to check/fix this? Thanks.

**Comment by strogonoff** [comment]
@ronaldtse

142b06a39304606b23a442d5088bd1fa9d2451da decided to reorganize OGC documentation without updating links.

- I don’t understand why reorganization had to happen. We have a convention where authoring guide for every flavor uses a consistent pattern ([1](https://www.metanorma.org/author/mpfa/authoring/), [2](https://www.metanorma.org/author/mpfa/authoring/), [3](https://www.metanorma.org/author/bipm/authoring/), [4](https://www.metanorma.org/author/iho/authoring/), [5](https://www.metanorma.org/author/csa/authoring/)).
- Any time a page is renamed or deleted, it’s *very important* that a redirect is left in place. I added [a warning in README](https://github.com/metanorma/metanorma.org/blob/main/README.adoc#avoiding-dead-links-with-redirects) about that.

**Comment by ronaldtse** [comment]
@strogonoff I believe the reorg was needed to separate the new topic of "OGC Requirements", it was our first flavor that did machine-readable requirements. Thanks @strogonoff !

**Comment by ronaldtse** [comment]
The link now works. Thanks again @letmaik @strogonoff !
