### ISSUE TITLE
Add "Numeric range" encoding guidance

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma.org#617]
*In relation to https://github.com/metanorma/metanorma-standoc/issues/641*

We need to document the way to encode en-dashes for representing
numeric ranges in Metanorma.

**Comment by ronaldtse** [comment]
@manuelfuenmayor there's no need to close this issue after making the PR -- if you include the phrase "Fixes #617" in the PR, once the PR is merged, this issue will be closed and linked to that.

**Comment by manuelfuenmayor** [comment]
Oh, I see. Ok @ronaldtse 👍
