### ISSUE TITLE
Remove `/ats/` segment from Abstract Test examples on the OGC part of the metanorma.org documentation.

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma.org#620]
The `/ats/` was used in error in version 1.0.0 of the CityGML3 CM standard. For consistency with OGC Naming Authority policy, the segments should have been `/conf/` instead.

Please remove the `/ats/` segment from Abstract Test examples on the [OGC part](https://www.metanorma.org/author/ogc/topics/requirements/) of the metanorma.org documentation.

Alternatively, you may simply remove the CItyGML examples since the documentation already offers examples from DGGS.

![Screenshot 2022-07-08 at 12 37 03](https://user-images.githubusercontent.com/18121038/177985352-3775310f-a9cd-4f3a-944e-44c7b09c62d9.png)

**Comment by ronaldtse** [comment]
Thank you @ghobona , we will update the documentation as suggested.
