### ISSUE TITLE
correction regarding documentation: bibliography section, example 1

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma.org#675]
in this url
https://www.metanorma.org/author/topics/document-format/bibliography/
example 1 (in the light blue area) the following text contains an error

the text: 
"In ISO, the “Normative references” clause is stated in Clause 3..." 
incorrectly says that Normative refs are in clause 3
the corrected text should read:
"In ISO documents, the “Normative references” clause is designated as Clause 2..."

additionally, lower down in the example, this text (comment) should also be revised to say "Clause 2"
// This is Clause 3 of an ISO deliverable 

please change when possible, thank you

**Comment by ronaldtse** [comment]
Thank you @ReesePlews for the report! Will fix ASAP.

**Comment by ronaldtse** [comment]
This is now fixed. <img width="774" alt="Screen Shot 2022-11-06 at 1 38 43 PM" src="https://user-images.githubusercontent.com/11865/200155997-c3cd70bc-f260-453b-88fb-bb1bf57b5b49.png">

**Comment by ReesePlews** [comment]
@ronaldtse thank you for fixing that
