### ISSUE TITLE
documentation:  404 error on link in documentation...

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma.org#679]
on this page:
https://www.metanorma.org/author/ieee/authoring-guide/cross-references/
in this list (at the top of the text)

There are four types of cross-references:

    Internal references to a section, image, table, etc.

    [Bibliographic entries](https://www.metanorma.org/author/topics/sections/entering_bib.adoc)

    Hyperlinks to an external source (e.g., a link to a website)

this link: https://www.metanorma.org/author/topics/sections/entering_bib.adoc gives a 404

**Comment by ronaldtse** [comment]
Thank you @ReesePlews ! Fixing it now.
