### ISSUE TITLE
documentation issue: "in_organization" is not a listed span category but is present in an example...

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma.org#682]
on this page....

https://www.metanorma.org/author/topics/document-format/bibliography

in the span categories shown above example 11 does not show a "in_organization" category but the example does show an "in_organization" category.

**Comment by opoudjis** [comment]
> * `in_surname`, `in_initials`, `in_givenname`, `in_organization`: Name of contributor for containing
bibliographic item (for types `inbook, inproceedings, incollection`, the author or more usually editor
of the book, proceedings, collection containing the item. So `in_surname.editor`, `in_givenname.editor`
give the name of the editor of the book or proceedings that a paper is included in).

````
* [[[A, B]]],
  span:surname[Wozniak], span:initials[S.] & span:givenname[Steve] span:surname[Jobs].
  span:date.issued[1991].
  span:date[1996].
  span:title[_Work_].
  In span:in_surname.editor[Gates], span:in_initials.editor[W. H] &
  span:in_organization[UNICEF],
  span:in_title[Collected Essays].
  _span:series[Bibliographers Anonymous]._
  span:docid.ISO[ISO 1234].
  span:pubplace[Geneva]:
  span:publisher[International Standardization Organization].
  span:uri.citation[http://www.example.com].
  vol. span:volume[5],
  pp. span:pages[2-21]
  span:type[inbook]
````

> Note the distinction in the example between Wozniak and Jobs (authors of the paper),
and Gates and UNICEF (editors of the book including the paper). Similarly, note the
distinction between the title of the paper (_Work_), and the title of the book including
the paper (_Collected Essays_).

**Comment by ReesePlews** [comment]
@opoudjis thank you very much for the detailed explanation, this is quite helpful.

**Comment by opoudjis** [comment]
> @opoudjis thank you very much for the detailed explanation, this is quite helpful. is the documentation also updated every two weeks, or is it on a different schedule?

Ad hoc, I'm afraid. Updates pile up for Ronald to update, and there is no formal release process, or change log (apart from what is in the associated github repo: https://github.com/metanorma/metanorma.org
