### ISSUE TITLE
Document `:presentation-metadata-*:` attributes will be exposed to XML/HTML and its applicability to BSI

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#712]
This task is to document that `:presentation-metadata-*:` attributes will be exposed to XML/HTML and its applicability to BSI.

Flavor-specific documentation:
* BSI: `:presentation-metadata-layout-columns: 1` sets columns to 1 for BSI PAS/Flex layouts.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-bsi/issues/336#issuecomment-1449548233_

**Comment by opoudjis** [comment]
I've assigned you as well, @Intelligent2013, because I haven't tracked all such attributes.

**Comment by Intelligent2013** [comment]
BSI specific `:presentation-metadata-` attributes:
```
:presentation-metadata-color-cover-background:
:presentation-metadata-color-cover-title:
:presentation-metadata-color-secondary-shade-1:
:presentation-metadata-color-secondary-shade-2:
:presentation-metadata-color-secondary-shade-3:
:presentation-metadata-color-secondary-shade-4:
:presentation-metadata-color-list-label:
:presentation-metadata-color-clause-union-background:
:presentation-metadata-color-backpage-background:
:presentation-metadata-layout-columns:
```

They all described in
https://github.com/metanorma/metanorma.org/blob/doc20230209/author/bsi/ref/document-attributes.adoc
