### ISSUE TITLE
Discrepancy in the ISO document attribute `:publisher:`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma.org#725]
The source issues: https://github.com/metanorma/iso-iec-2382/issues/4#issuecomment-1805447932, https://github.com/metanorma/iso-iec-2382/pull/8#issuecomment-1805448231

From https://www.metanorma.org/author/iso/ref/document-attributes/ - slash-delimited value:
<img width="602" alt="Screenshot 2023-11-10 at 6 12 45 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/d41e8073-5ef4-452b-b4ec-6baedfe74159">

But in https://www.metanorma.org/author/ref/document-attributes/#document-info specified `semicolon-delimited`.

**Comment by opoudjis** [comment]
Want to delay fixing this until @mico finishes https://github.com/metanorma/pubid-iec/issues/127, so that I can be sure that identifiers using delimited publishers are corrected rendered in IEC.
