### ISSUE TITLE
Clean up "Learn" sections and the exercises

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#731]

**Comment by kwkwan** [comment]
@ronaldtse I have made some changes in https://github.com/metanorma/metanorma.org/pull/740.  Please check.

**Comment by kwkwan** [comment]
Closed https://github.com/metanorma/metanorma.org/issues/731 as completed via https://github.com/metanorma/metanorma.org/pull/740.

**Comment by ronaldtse** [comment]
Thanks @kwkwan. Next time please rebase the commits instead of merge.
