### ISSUE TITLE
I assume the meta data tag aren't working properly?

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma.org#767]
Hi there, I was going through the authoring docs, and seems like some metadata tags are being shown in the generated site:

**Example URL:** https://www.metanorma.org/author/basics/what/

**Screenshots:**

<img width="553" alt="Screenshot 2024-04-20 at 13 58 31" src="https://github.com/metanorma/metanorma.org/assets/1220911/9366d508-b0a2-4c69-9da5-d059dde43d02">
<img width="780" alt="Screenshot 2024-04-20 at 13 58 39" src="https://github.com/metanorma/metanorma.org/assets/1220911/83b3507b-b3c4-4cfd-b5b4-cdd71a41be2a">

cc: @ronaldtse, @ni4 - can we get someone to look into that?

**Comment by ronaldtse** [comment]
@abunashir yes this is a known problem. The problem is that the Jekyll-AsciiDoc gem doesn’t support the tags.

**Comment by anermina** [comment]
@ronaldtse @abunashir According to the AsciiDoc documentation, these tags should be written as comments, i.e.
````
// tag::tutorial[]

text

// end::tutorial[] 
````

I have tested whether the tags encoded this way are working using the `include` option, and they seem to be working just fine.

Could this solve our issue? If yes, I can apply the changes in all the affected files.

**Comment by ronaldtse** [comment]
Thank you @anermina ! I've made the PR #789 .
