### ISSUE TITLE
Add content: Http links inside http macros

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma.org#780]
Http links inside the content of http macro must be escaped.
For example, this: `http://example.com[http://example.com/]`, must be written as this ` http://example.com[\http://example.com/]`.

Add this clarification (possibly) in this section: https://www.metanorma.org/author/topics/document-format/xrefs/#hyperlinks

**Comment by opoudjis** [comment]
I'd argue it's https://www.metanorma.org/author/ref/asciidoc-tips/
