### ISSUE TITLE
Tutorial layout is broken

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/metanorma.org#782]
### Steps to reproduce

* Go to https://www.metanorma.org/learn/tutorial_complete/
* Scroll down to see broken layout (this screenshot is a zoomed-out view of the page.  Notice the varying margins, and the relative sizes of the text vs the images):

<img width="2184" alt="Screenshot 2024-06-11 at 14 49 11" src="https://github.com/metanorma/metanorma.org/assets/2649467/bf994537-be75-4dfe-b85b-6194f0c624cc">

More broken layout when scrolling down:

<img width="798" alt="Screenshot 2024-06-11 at 14 51 10" src="https://github.com/metanorma/metanorma.org/assets/2649467/d90bcae1-1bb0-4e17-8d52-efe269903f61">

### Expected outcome

* All texts and images to be more or less aligned.
* Image dimensions to be scaled to match normal page width.

### Environment

* Firefox
* Safari

**Comment by opoudjis** [comment]
No assignee, no action. And it won't be me....

**Comment by opoudjis** [comment]
Who is looking after metanorma.org display? @strogonoff ? @ronaldtse ? A yet-unnamed front-end dev?

**Comment by strogonoff** [comment]
I fixed the exact same problem on riffol.com last week. I remember checking MN site and it was unaffected. I’ll have a look.

**Comment by strogonoff** [comment]
I see that it affects the tutorial, but not the rest of the docs. It likely has to do with misconfigured  layout for those pages.

**Comment by strogonoff** [comment]
@opoudjis From what I can see after a brief look, the page you linked to is an orphan page not linked to from anywhere on MN site.

The actual tutorial is linked to by the fat “Start Tutorial” button and the URL is https://www.metanorma.org/learn/lessons/lesson-1-1/.

- If there are links to https://www.metanorma.org/learn/tutorial_complete/ from within the current MN site, let me know what they are.
- If there are links to https://www.metanorma.org/learn/tutorial_complete/ _only_ from the outside, we may potentially want to set up a redirect from your link to https://www.metanorma.org/learn/lessons/lesson-1-1/ (and update those external links if we can).

**Comment by strogonoff** [comment]
The actual layout problem is fixed now as of 955cc12 and verified on production site.

I think it may be OK to duplicate the entire tutorial if it suits some particular purpose, but from SEO standpoint it may be suboptimal since search engines tend to discourage content duplication.

**Comment by strogonoff** [comment]
For future reference, the issue arises when a page doesn’t have the correct layout specified (either through defaults in global config or in frontmatter).
