### ISSUE TITLE
Missing content on semantic change history

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.org#796]
This is an interesting topic because it feels that some information was lost:

* https://github.com/search?q=org%3Ametanorma%20doc-history-misc-container&type=code

There are 4 entries that refer to this "semantic document history" location but it doesn't exist.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma.org/issues/793#issuecomment-2208155467_

**Comment by opoudjis** [comment]
This has happened a lot as a result of the two years of ignored PRs, and I've often had to go back to the source ticket to find the missing PR in metanorma.org. Did you do so, @ronaldtse ? When this happens again, please do so, or get me to.

**Comment by ronaldtse** [comment]
Yes this is fixed now, with content rewritten from old commits.
